require: rubocop-bridgetown

inherit_gem:
  rubocop-bridgetown: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - .gitignore
    - .rspec
    - .rubocop.yml

    - Rakefile
    - bridgetown.automation.rb
    - Gemfile.lock
    - "*.gemspec"
    - CHANGELOG.md
    - LICENSE.txt
    - README.md

    - script/**/*
    - vendor/**/*
    - spec/**/*

Metrics/AbcSize:
  Exclude:
    - lib/bridgetown-cloudinary/utils.rb